### ISSUE TITLE
Observe in queue?

### ISSUE THREAD

**Issue by malcommac** [flowtoolz/SwiftObserver#3]
Is possible to observe value change in a specific `DispatchQueue`?

**Comment by flowtoolz** [comment]
> Is possible to observe value change in a specific `DispatchQueue`?

Hi Daniele, sorry for my ridiculously long delay. 

Also: SwiftObserver is not dead, I use it every day. I just had no need for changes :)

Custom queues are currently not possible but would be quite straight forward to implement.  You could make a PR :) 

I've added a type dependency diagram to provide some overview: https://github.com/flowtoolz/SwiftObserver/blob/master/Documentation/Architecture.pdf
The red types would be directly effected by an additional parameter for Observers, like `observe(<other parameters>, on queue: DispatchQueue) ...

Btw, great work with SwiftDate! 👍
