### ISSUE TITLE
Compiling with swift-tools-version:5.1 yields error

### ISSUE THREAD

**Issue by din** [flowtoolz/SwiftObserver#4]
**Describe the bug**
When I try to make a Swift Package which depends on SwiftObserver, it fails to compile with errors pointing to the SwiftyToolz sources. 

**To Reproduce**
1. Create empty Swift package
2. Add SwiftObserver as a dependency using `.package(url: "https://github.com/flowtoolz/SwiftObserver.git",
                .upToNextMajor(from: "5.0.1"))`
3. Try to build
4. Error happens

<img width="1115" alt="Screenshot 2019-11-07 at 11 23 27" src="https://user-images.githubusercontent.com/78038/68372007-1684c480-0151-11ea-871f-4f407f4c9cfd.png">

**Expected behavior**
The build should be successful.

**Desktop:**
 - macOS 10.15
 - Xcode 11.1

**Comment by din** [comment]
Temporary solution is to use the following dependency configuration: 

```
.package(url: "https://github.com/flowtoolz/SwiftObserver.git",
                .upToNextMajor(from: "5.0.1")),
.package(url: "https://github.com/flowtoolz/SwiftyToolz.git",
                 .exact("1.4.3"))
```

**Comment by flowtoolz** [comment]
Hey @din , Thanks for your detailed feedback!

The versions and dependencies are now up to date, so it should work via SPM.
Cocoapod will follow.

Let me know if there's anything else I should think about.
